### ISSUE TITLE
Alexa Test Automation

### ISSUE THREAD

**Issue by codeforequity-at** [KayLerch/alexa-skills-kit-tester-java#5]
Dear Kay,

I am glad that Alexa Team recognized the need for automated testing of Alexa skills. Last year I initiated the projects "[TestMyBot](https://github.com/codeforequity-at/testmybot)" and "[Botium](https://github.com/codeforequity-at/botium-core)" to address to need for automated testing of Chatbots in general, and my approach is the same to yours (scripting the conversations). One of the next steps for my projects will be to support automated testing of Alexa Skills, as one of our clients (Vienna based telecommunication provider) will publish some of them soon. Your project is a great inspiration. 

So, I have no issue here, I just wanted to get in contact with you. If you are interested in my Github projects, please feel free to join or drop me a line (hello@testmybot.com).

Best Regards,
Florian

**Comment by KayLerch** [comment]
We got in contact. Thanks for the great blogpost you wrote about your own test tool
