### ISSUE TITLE
Bad Request: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by BadaBoomi** [KayLerch/alexa-skills-kit-tester-java#8]
Double checked my configuration but I'm unable to perform any test requests. I am trying with a very basic yml file:

`configuration:
  endpoint:
    type:     InvocationApi 
    region:   EU
    locale:   de-DE

Launch:
  - response.shouldEndSession == false`

Regardless if I start it localy (java -jar alexa-skills-kit-tester-java-1.1.0.jar -f ...) or via lambda test, it allways ends up with log entries here:

`
START RequestId: 7b53fda1-a2f1-11e8-8ac0-c188c69c348e Version: $LATEST
[INFO] Reading out *.yml conversation script files in folder '' in bucket 'testmentaltrainerskill-testscriptbucket-5ywy7vc3j5lw'
[INFO] Found 1 conversation script files in bucket 'testmentaltrainerskill-testscriptbucket-5ywy7vc3j5lw'
[INFO] Load conversation script file test.yml from S3 bucket testmentaltrainerskill-testscriptbucket-5ywy7vc3j5lw

[START] session start request with sessionId 'SessionId.b979b7bd-a72f-4d00-b638-3c753457c058' ...
Bad Request: java.lang.IllegalArgumentException
java.lang.IllegalArgumentException: Bad Request
	at org.apache.commons.lang3.Validate.inclusiveBetween(Validate.java:922)
	at io.klerch.alexa.test.client.endpoint.AlexaApiEndpoint.fire(AlexaApiEndpoint.java:99)
	at io.klerch.alexa.test.client.AlexaClient.fire(AlexaClient.java:125)
	at io.klerch.alexa.test.client.AlexaClient.fire(AlexaClient.java:117)
	at io.klerch.alexa.test.client.AlexaSession.<init>(AlexaSession.java:56)
	at io.klerch.alexa.test.client.AlexaClient.startSession(AlexaClient.java:156)
	at io.klerch.alexa.test.client.AlexaClient.startScript(AlexaClient.java:166)
	at io.klerch.alexa.test.Lambda.handleRequest(Lambda.java:62)

END RequestId: 7b53fda1-a2f1-11e8-8ac0-c188c69c348e
REPORT RequestId: 7b53fda1-a2f1-11e8-8ac0-c188c69c348e	Duration: 806.57 ms	Billed Duration: 900 ms 	Memory Size: 1024 MB	Max Memory Used: 97 MB	`

**Comment by BadaBoomi** [comment]
some more information...
Class in which error occurs is:
io.klerch.alexa.test.client.endpoint.AlexaApiEndpoint
Method is: public Optional<AlexaResponse> fire(final AlexaRequest request, final String payload)
Line is:  Validate.inclusiveBetween(200, 399, httpResponse.getStatusLine().getStatusCode(), httpResponse.getStatusLine().getReasonPhrase());

content of objects:
**payload**= {"version":"1.0","session":{"new":true,"sessionId":"SessionId.ba9cf97b-cae6-4921-92fd-8f12240f3f78","application":{"applicationId":"amzn1.ask.skill...."},"user":{"userId":"amzn1.ask.account.W4R...."}},"context":{"System":{"application":{"applicationId":"amzn1.ask.skill.941..."},"user":{"userId":"amzn1.ask.account.W4R...."},"device":{"supportedInterfaces":{}},"apiEndpoint":"https://api.eu.amazonalexa.com/","apiAccessToken":null}},"request":{"type":"SessionStartedRequest","requestId":"EdwRequestId.72339312-a245-46cc-9a6e-ea8871e3cd5a","timestamp":"2018-08-18T15:08:18Z","locale":"de-DE"}}
**statusCode**=400

original **httpResponse**=
HTTP/1.1 400 Bad Request [Server: Server, Date: Sat, 18 Aug 2018 15:11:47 GMT, Content-Type: application/json, Connection: keep-alive, x-amzn-RequestId: 067cd21b-a2f9-11e8-af9c-35bf11180ee8, X-Amz-Date: Sat, 18 Aug 2018 15:11:47 GMT, x-amzn-ErrorType: BadRequestException:http://internal.amazon.com/coral/com.amazon.alexa.skillmanagement/, Vary: Accept-Encoding,User-Agent] org.apache.http.client.entity.DecompressingEntity@649725e3

**Comment by e-bar** [comment]
Hey @BadaBoomi, did you figure out why you were gotting `400 Bad Request` as http response.

I'm dealing with the same situation.
